"""framework_port — the public Facade contract of the Hongsheng Works demo.

The application depends only on this package (protocol + DTOs + errors +
constants). It must never import a concrete backend or any external framework
module directly; backends are selected at startup via configuration.
"""

from .constants import (  # noqa: F401
    ACTION_INVENTORY_ADJUST,
    ACTION_INVENTORY_RECEIPT,
    ACTION_PRODUCTION_ORDER_COMPLETE,
    ACTION_PRODUCTION_ORDER_CREATE,
    ACTION_PRODUCTION_ORDER_ISSUE_MATERIAL,
    ACTION_PRODUCTION_ORDER_RELEASE,
    ACTION_PRODUCTION_ORDER_REPORT_PROGRESS,
    ACTION_QUOTATION_ACCEPT,
    ACTION_QUOTATION_SUBMIT,
    ACTION_SALES_ORDER_CONFIRM,
    ACTION_SALES_ORDER_REQUEST_CHANGE,
    ACTION_SHIPMENT_REQUEST,
    APPROVAL_EXPEDITE_PURCHASE,
    BUSINESS_ACTIONS,
    FRESHNESS_FRESH,
    FRESHNESS_UNKNOWN,
    GOVERNED_CARRIER_DISPATCH,
    MODE_LICENSED_FRAMEWORK,
    MODE_PUBLIC_SIMULATION,
    PERM_CANCEL,
    PERM_CREATE,
    PERM_EDIT,
    PERM_EXECUTE,
    PERM_VIEW,
    RECORD_CUSTOMER,
    RECORD_INVENTORY_ITEM,
    RECORD_INVENTORY_MOVEMENT,
    RECORD_MATERIAL,
    RECORD_MATERIAL_REQUIREMENT,
    RECORD_PRICE_BOOK_ENTRY,
    RECORD_PRODUCT,
    RECORD_PRODUCTION_ORDER,
    RECORD_QUOTATION,
    RECORD_QUOTATION_LINE,
    RECORD_SALES_ORDER,
    RECORD_SALES_ORDER_LINE,
    RECORD_SHIPMENT,
    RECORD_TYPES,
    RESULT_ACCEPTED,
    RESULT_AMBIGUOUS,
    RESULT_REJECTED,
    ROLE_ADMIN,
    ROLE_FACTORY,
    ROLE_OWNER,
    ROLE_SALES,
    ROLE_WAREHOUSE,
    VERDICT_MATCHED_DERIVED,
    VERDICT_UNOBSERVABLE,
)
from .dtos import (  # noqa: F401
    ActionResult,
    ApprovalPolicy,
    ApprovalView,
    AuditEntry,
    BackendCapabilities,
    BackendConfig,
    ConversationMessage,
    EvidenceVerification,
    ExternalApplyResult,
    ExternalReadResult,
    GovernedActionView,
    HandoffView,
    NotificationView,
    Principal,
    Record,
    RecordRef,
    ReconciliationResult,
    RoleRule,
    TaskView,
    UserView,
)
from .errors import (  # noqa: F401
    AuthenticationFailed,
    AuthorizationDenied,
    BackendUnavailable,
    DuplicateRequest,
    FacadeError,
    NotFound,
    NotSupportedInBackend,
    RetryRefused,
    ValidationFailed,
    VersionConflict,
)
from .protocol import ExternalSystemSimulator, ManufacturingBackend  # noqa: F401
